services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: planifik-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - planifik_data:/var/lib/postgresql/data

  app:
    image: ghcr.io/henriquecolini/planifik:latest
    restart: always
    container_name: planifik-app
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NODE_ENV: production
    ports:
      - "3000:3000"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    container_name: planifik-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json  # for GHCR auth
    environment:
      WATCHTOWER_POLL_INTERVAL: 30         # check every 30 seconds
      WATCHTOWER_CLEANUP: "true"           # remove old images after update
      WATCHTOWER_INCLUDE_STOPPED: "false"
    command: planifik-app

volumes:
  planifik_data:
